language: node_js
node_js:
- '0.12'
notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/aae9117008dad1557aac'
    on_success: change
    on_failure: always
    on_start: false
script: "npm run-script ci"
